- name: user
  hosts: demo2
  tasks:
    - name: Install links
      apt:
        name: links
        state: absent
        update-cache: yes
      become: true  
      register: out # регистрируем переменную для дебага
    - debug:
        var: out # вкл. дебаг и выводим в переменную 
    #   #debugger: always
