---
- name: Preconfig
  vars_prompt: ## Ввод переменной
  - name: hosts
    prompt: "Enter the hosts group name"
    private: no
  hosts: "{{hosts}}"
  become: true

  tasks:
    - name: Check hosts
      block:
        - name: ping hosts
          ping:

    - name: Install packages
      block:
        - name: Install htop  
          apt:
            name: htop
            state: present
            update-cache: yes    

    # block:
    #   - name: Install htop
    #     apt:
    #       name: htop
    #       state: present
    #       update-cache: yes

