---
name: Preconfig
  # vars_prompt: ## Ввод переменной
  # - name: hosts
  #   prompt: "Enter the hosts group name"
  #   private: no
  # hosts: "{{hosts}}"
  hosts: demo
  become: true

  tasks:
    block:
      - name: Ping hosts
        ping:

    block:
      - name: Install htop
        apt:
          name: htop
          state: present
          update-cache: yes

