---
- name: ping
  vars_prompt: ## Ввод переменной
  - name: hosts
    prompt: "Введите группу хостов"
    private: no

  hosts: "{{hosts}}"
  # vars in group_vars/demo/vars.yml
  # vars_files:
  #   - ./my_vars.yml
  # vars_prompt: ## Ввод переменной
  #   - name: user
  #     prompt: "Введите пользователя"
  #     private: no
  tasks:
    - name: Ping
      # vars:
      #   user: av2
      ping:
      #become: true # от root
    #   register: out # регистрируем переменную для дебага
    # - debug:
    #     var: out # вкл. дебаг и выводим в переменную 

      debugger: always
      ## команды в дебагере:
        ## p task (Вывод task name)
        ## p task.args (Вывод аргументов задачи, котоые передавались в модуль)
        ## p task.vars (Вывод переменных в task)