---
- name: sleep
  hosts: demo
  tasks:
    - name: Preconfig block
      block:
        - name: sleep
          command: /bin/sleep 15
          async: 1000
          poll: 0
          become: true
          register: sleep
        - debug:
            var: sleep  

        - name: echo
          command: echo "Hello!! DONE"

   - name: Check sleep status
     async_status: 
       jid: "{{ sleep.ansible_job_id }}"    
     register: job_result
     until: job_result.finished   
     retries: 100
     delay: 1
     become: true
