---
- name: user
  hosts: demo
  # vars_files:
  #   - ./my_vars.yml
  tasks:
    - name: Create user
      # vars:
      #   user: av2
      user:
        name: "{{ user }}"
        state: present
      become: true  