---
- name: user
  hosts: demo
  # vars in group_vars/demo/vars.yml
  # vars_files:
  #   - ./my_vars.yml
  # vars_prompt: ## Ввод переменной
  #   - name: user
  #     prompt: "Введите пользователя"
  #     private: no
  tasks:
    - name: Create user
      # vars:
      #   user: av2
      user:
        name: "{{ user }}"
        state: present
      become: true
    #   register: out # регистрируем переменную для дебага
    # - debug:
    #     var: out # вкл. дебаг и выводим в переменную 

      debugger: always
      ## команды в дебагере:
        ## p task (Вывод task name)
        ## p task.args (Вывод аргументов задачи, котоые передавались в модуль)
        ## p task.vars (Вывод переменных в task)