---
- name: user
  hosts: demo
  # any_errors_fatal: true
  tasks:
    - name: Preconfig block
      block:
        - name: Create user
          vars:
            user: av2
          user:
            name: "{{ user }}"
            state: absent
          register:  error # регистрируем переменную 
          # ignore_errors: true
        - debug:
            var: error # вкл. дебаг и выводим в переменную 

        - name: Install links
          apt:
            name: links
            update-cache: yes
          register: error # регистрируем переменную для дебага
        - debug:
            var: error # вкл. дебаг и выводим в переменную 
        #   #debugger: always

      become: true
      when: ansible_facts['distribution'] == 'Ubuntu'  # Условия выполнения блока     
      rescue: ## Обработка ошибки
        - name: Some error print
          debug:
            var: error
      always:
        - name: Reboot
          debug:
            msg: "Rebooting"
              
            