---
- name: Preconfig
  hosts: cirpk
  tasks:
    - name: Docker install
      block:
        - name: add universe repository
          apt_repository:
            repo: " deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present

        - name: install additional packages
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            state: present
            update_cache: true
            cache_valid_time: 86400

        - name: Add Docker’s official GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            keyring: /usr/share/keyrings/docker-archive-keyring.gpg
            state: present

        - name: set up the stable repository
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update_cache: true
            filename: docker
          #debugger: always

        - name: Install Docker Engine
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
            update_cache: true

        - name: testing that docker is installed and restarted
          service:
            name: docker
            state: restarted
            enabled: true

      become: true

    - name: Docker-compose install
      block:
        - name: download the latest ver of Docker Compose
          uri:
            url: "https://api.github.com/repos/docker/compose/releases/latest"
            body_format: json
          register: page

        - name: install the latest ver of Docker Compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: true

    - name: complete installation
      block:
        - name: add user to docker group
          user:
            name: "{{ ansible_user }}"
            groups: "docker"
            append: true

        #- name: server reboot
        #  reboot:
      become: true

    - name: Softether install
      block:
        - name: сreate directory
          file:
            path: /home/softethervpn
            state: directory 

        - name: copy docker-compose
          copy:
              src: files/docker-compose.yaml
              dest: /home/softethervpn

        - name: copy server.config
          copy:
              src: files/vpn_server.config
              dest: /home/softethervpn      

        - name: docker-compose up
          command: PSK=987654321 USERS=av:1234qwer SPW=12345678 HPW=12345678 docker-compose -f /home/softethervpn/docker-compose.yaml up -d 

        #- name: copy config from container
        #  command: docker cp softethervpn:/usr/vpnserver/vpn_server.config ./home/softethervpn/         
