---
- name: Preconfig
  hosts: test
  tasks:
    - name: Docker install
      block:
        - name: add universe repository
          apt_repository:
            repo: " deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present