version: '3'
services:
  softethervpn:
    container_name: 'softethervpn'
    image: siomiz/softethervpn
    cap_add: 
      - NET_ADMIN
    # environment:
    #   - PSK=12345678
    #   - "USERS=av:1234qwer"
    #   - SPW=12345678
    #   - HPW=12345678
    restart: always
    volumes:
      - /home/softethervpn/vpn_server.config:/opt/vpn_server.config
    ports:
      # L2TP/IPSec
      - "500:500/udp"
      - "4500:4500/udp"
      - "1701:1701/tcp"
      # OpenVPN/SSTP
      - "443:443/tcp"
      - "1194:1194/udp"
      # SoftEther VPN (recommended by vendor)
      - "5555:5555/tcp"
      - "992:992/tcp"
